//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace DAL.DataEntities
{
    public partial class CompositionRule_Type : IDataEntity
    {
        #region Primitive Properties
    
        public virtual int ID
        {
            get;
            set;
        }
    
        public virtual string Name
        {
            get;
            set;
        }

        #endregion
        #region Navigation Properties
    
        public virtual ICollection<CompositionRule> CompositionRules
        {
            get
            {
                if (_compositionRules == null)
                {
                    var newCollection = new FixupCollection<CompositionRule>();
                    newCollection.CollectionChanged += FixupCompositionRules;
                    _compositionRules = newCollection;
                }
                return _compositionRules;
            }
            set
            {
                if (!ReferenceEquals(_compositionRules, value))
                {
                    var previousValue = _compositionRules as FixupCollection<CompositionRule>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= FixupCompositionRules;
                    }
                    _compositionRules = value;
                    var newValue = value as FixupCollection<CompositionRule>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += FixupCompositionRules;
                    }
                }
            }
        }
        private ICollection<CompositionRule> _compositionRules;

        #endregion
        #region Association Fixup
    
        private void FixupCompositionRules(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (CompositionRule item in e.NewItems)
                {
                    item.CompositionRule_Types = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (CompositionRule item in e.OldItems)
                {
                    if (ReferenceEquals(item.CompositionRule_Types, this))
                    {
                        item.CompositionRule_Types = null;
                    }
                }
            }
        }

        #endregion
    }
}
