//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace DAL.DataEntities
{
    public partial class SelectionState : IDataEntity
    {
        #region Primitive Properties
    
        public virtual int ID
        {
            get;
            set;
        }
    
        public virtual string Name
        {
            get;
            set;
        }

        #endregion
        #region Navigation Properties
    
        public virtual ICollection<FeatureSelection> FeatureSelections
        {
            get
            {
                if (_featureSelections == null)
                {
                    var newCollection = new FixupCollection<FeatureSelection>();
                    newCollection.CollectionChanged += FixupFeatureSelections;
                    _featureSelections = newCollection;
                }
                return _featureSelections;
            }
            set
            {
                if (!ReferenceEquals(_featureSelections, value))
                {
                    var previousValue = _featureSelections as FixupCollection<FeatureSelection>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= FixupFeatureSelections;
                    }
                    _featureSelections = value;
                    var newValue = value as FixupCollection<FeatureSelection>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += FixupFeatureSelections;
                    }
                }
            }
        }
        private ICollection<FeatureSelection> _featureSelections;

        #endregion
        #region Association Fixup
    
        private void FixupFeatureSelections(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (FeatureSelection item in e.NewItems)
                {
                    item.SelectionState = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (FeatureSelection item in e.OldItems)
                {
                    if (ReferenceEquals(item.SelectionState, this))
                    {
                        item.SelectionState = null;
                    }
                }
            }
        }

        #endregion
    }
}
