//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace DAL.DataEntities
{
    public partial class UITemplate : IDataEntity
    {
        #region Primitive Properties
    
        public virtual int ID
        {
            get;
            set;
        }
    
        public virtual int UserID
        {
            get { return _userID; }
            set
            {
                if (_userID != value)
                {
                    if (User != null && User.ID != value)
                    {
                        User = null;
                    }
                    _userID = value;
                }
            }
        }
        private int _userID;
    
        public virtual string Name
        {
            get;
            set;
        }
    
        public virtual string Content
        {
            get;
            set;
        }
    
        public virtual Nullable<System.DateTime> CreatedDate
        {
            get;
            set;
        }
    
        public virtual Nullable<System.DateTime> LastModifiedDate
        {
            get;
            set;
        }
    
        public virtual string Stylesheet
        {
            get;
            set;
        }

        #endregion
        #region Navigation Properties
    
        public virtual User User
        {
            get { return _user; }
            set
            {
                if (!ReferenceEquals(_user, value))
                {
                    var previousValue = _user;
                    _user = value;
                    FixupUser(previousValue);
                }
            }
        }
        private User _user;
    
        public virtual ICollection<Configuration> Configurations
        {
            get
            {
                if (_configurations == null)
                {
                    var newCollection = new FixupCollection<Configuration>();
                    newCollection.CollectionChanged += FixupConfigurations;
                    _configurations = newCollection;
                }
                return _configurations;
            }
            set
            {
                if (!ReferenceEquals(_configurations, value))
                {
                    var previousValue = _configurations as FixupCollection<Configuration>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= FixupConfigurations;
                    }
                    _configurations = value;
                    var newValue = value as FixupCollection<Configuration>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += FixupConfigurations;
                    }
                }
            }
        }
        private ICollection<Configuration> _configurations;

        #endregion
        #region Association Fixup
    
        private void FixupUser(User previousValue)
        {
            if (previousValue != null && previousValue.UITemplates.Contains(this))
            {
                previousValue.UITemplates.Remove(this);
            }
    
            if (User != null)
            {
                if (!User.UITemplates.Contains(this))
                {
                    User.UITemplates.Add(this);
                }
                if (UserID != User.ID)
                {
                    UserID = User.ID;
                }
            }
        }
    
        private void FixupConfigurations(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (Configuration item in e.NewItems)
                {
                    item.UITemplate = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (Configuration item in e.OldItems)
                {
                    if (ReferenceEquals(item.UITemplate, this))
                    {
                        item.UITemplate = null;
                    }
                }
            }
        }

        #endregion
    }
}
