//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.EntityClient;

namespace DAL.DataEntities
{
    public partial class DataEntities : ObjectContext
    {
        public const string ConnectionString = "name=DataEntities";
        public const string ContainerName = "DataEntities";
    
        #region Constructors
    
        public DataEntities()
            : base(ConnectionString, ContainerName)
        {
            this.ContextOptions.LazyLoadingEnabled = true;
        }
    
        public DataEntities(string connectionString)
            : base(connectionString, ContainerName)
        {
            this.ContextOptions.LazyLoadingEnabled = true;
        }
    
        public DataEntities(EntityConnection connection)
            : base(connection, ContainerName)
        {
            this.ContextOptions.LazyLoadingEnabled = true;
        }
    
        #endregion
    
        #region ObjectSet Properties
    
        public ObjectSet<Attribute_DataType> Attribute_DataTypes
        {
            get { return _attribute_DataTypes  ?? (_attribute_DataTypes = CreateObjectSet<Attribute_DataType>("Attribute_DataTypes")); }
        }
        private ObjectSet<Attribute_DataType> _attribute_DataTypes;
    
        public ObjectSet<Attribute> Attributes
        {
            get { return _attributes  ?? (_attributes = CreateObjectSet<Attribute>("Attributes")); }
        }
        private ObjectSet<Attribute> _attributes;
    
        public ObjectSet<Feature> Features
        {
            get { return _features  ?? (_features = CreateObjectSet<Feature>("Features")); }
        }
        private ObjectSet<Feature> _features;
    
        public ObjectSet<Model> Models
        {
            get { return _models  ?? (_models = CreateObjectSet<Model>("Models")); }
        }
        private ObjectSet<Model> _models;
    
        public ObjectSet<User> Users
        {
            get { return _users  ?? (_users = CreateObjectSet<User>("Users")); }
        }
        private ObjectSet<User> _users;
    
        public ObjectSet<Attribute_Type> Attribute_Types
        {
            get { return _attribute_Types  ?? (_attribute_Types = CreateObjectSet<Attribute_Type>("Attribute_Types")); }
        }
        private ObjectSet<Attribute_Type> _attribute_Types;
    
        public ObjectSet<Relation_Type> Relation_Types
        {
            get { return _relation_Types  ?? (_relation_Types = CreateObjectSet<Relation_Type>("Relation_Types")); }
        }
        private ObjectSet<Relation_Type> _relation_Types;
    
        public ObjectSet<Relation> Relations
        {
            get { return _relations  ?? (_relations = CreateObjectSet<Relation>("Relations")); }
        }
        private ObjectSet<Relation> _relations;
    
        public ObjectSet<GroupRelation_Type> GroupRelation_Types
        {
            get { return _groupRelation_Types  ?? (_groupRelation_Types = CreateObjectSet<GroupRelation_Type>("GroupRelation_Types")); }
        }
        private ObjectSet<GroupRelation_Type> _groupRelation_Types;
    
        public ObjectSet<GroupRelation> GroupRelations
        {
            get { return _groupRelations  ?? (_groupRelations = CreateObjectSet<GroupRelation>("GroupRelations")); }
        }
        private ObjectSet<GroupRelation> _groupRelations;
    
        public ObjectSet<GroupRelation_To_Feature> GroupRelation_To_Feature
        {
            get { return _groupRelation_To_Feature  ?? (_groupRelation_To_Feature = CreateObjectSet<GroupRelation_To_Feature>("GroupRelation_To_Feature")); }
        }
        private ObjectSet<GroupRelation_To_Feature> _groupRelation_To_Feature;
    
        public ObjectSet<CompositionRule_Type> CompositionRule_Types
        {
            get { return _compositionRule_Types  ?? (_compositionRule_Types = CreateObjectSet<CompositionRule_Type>("CompositionRule_Types")); }
        }
        private ObjectSet<CompositionRule_Type> _compositionRule_Types;
    
        public ObjectSet<CompositionRule> CompositionRules
        {
            get { return _compositionRules  ?? (_compositionRules = CreateObjectSet<CompositionRule>("CompositionRules")); }
        }
        private ObjectSet<CompositionRule> _compositionRules;
    
        public ObjectSet<CustomRule> CustomRules
        {
            get { return _customRules  ?? (_customRules = CreateObjectSet<CustomRule>("CustomRules")); }
        }
        private ObjectSet<CustomRule> _customRules;
    
        public ObjectSet<AttributeValue> AttributeValues
        {
            get { return _attributeValues  ?? (_attributeValues = CreateObjectSet<AttributeValue>("AttributeValues")); }
        }
        private ObjectSet<AttributeValue> _attributeValues;
    
        public ObjectSet<Configuration> Configurations
        {
            get { return _configurations  ?? (_configurations = CreateObjectSet<Configuration>("Configurations")); }
        }
        private ObjectSet<Configuration> _configurations;
    
        public ObjectSet<FeatureSelection> FeatureSelections
        {
            get { return _featureSelections  ?? (_featureSelections = CreateObjectSet<FeatureSelection>("FeatureSelections")); }
        }
        private ObjectSet<FeatureSelection> _featureSelections;
    
        public ObjectSet<SelectionState> SelectionStates
        {
            get { return _selectionStates  ?? (_selectionStates = CreateObjectSet<SelectionState>("SelectionStates")); }
        }
        private ObjectSet<SelectionState> _selectionStates;
    
        public ObjectSet<UITemplate> UITemplates
        {
            get { return _uITemplates  ?? (_uITemplates = CreateObjectSet<UITemplate>("UITemplates")); }
        }
        private ObjectSet<UITemplate> _uITemplates;

        #endregion
    }
}
