//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace DAL.DataEntities
{
    public partial class Feature : IDataEntity
    {
        #region Primitive Properties
    
        public virtual int ID
        {
            get;
            set;
        }
    
        public virtual int ModelID
        {
            get { return _modelID; }
            set
            {
                if (_modelID != value)
                {
                    if (Model != null && Model.ID != value)
                    {
                        Model = null;
                    }
                    _modelID = value;
                }
            }
        }
        private int _modelID;
    
        public virtual string Name
        {
            get;
            set;
        }
    
        public virtual string Description
        {
            get;
            set;
        }
    
        public virtual Nullable<bool> IsRoot
        {
            get;
            set;
        }
    
        public virtual Nullable<double> XPos
        {
            get;
            set;
        }
    
        public virtual Nullable<double> YPos
        {
            get;
            set;
        }
    
        public virtual string Identifier
        {
            get;
            set;
        }

        #endregion
        #region Navigation Properties
    
        public virtual ICollection<Attribute> Attributes
        {
            get
            {
                if (_attributes == null)
                {
                    var newCollection = new FixupCollection<Attribute>();
                    newCollection.CollectionChanged += FixupAttributes;
                    _attributes = newCollection;
                }
                return _attributes;
            }
            set
            {
                if (!ReferenceEquals(_attributes, value))
                {
                    var previousValue = _attributes as FixupCollection<Attribute>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= FixupAttributes;
                    }
                    _attributes = value;
                    var newValue = value as FixupCollection<Attribute>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += FixupAttributes;
                    }
                }
            }
        }
        private ICollection<Attribute> _attributes;
    
        public virtual Model Model
        {
            get { return _model; }
            set
            {
                if (!ReferenceEquals(_model, value))
                {
                    var previousValue = _model;
                    _model = value;
                    FixupModel(previousValue);
                }
            }
        }
        private Model _model;
    
        public virtual ICollection<FeatureSelection> FeatureSelections
        {
            get
            {
                if (_featureSelections == null)
                {
                    var newCollection = new FixupCollection<FeatureSelection>();
                    newCollection.CollectionChanged += FixupFeatureSelections;
                    _featureSelections = newCollection;
                }
                return _featureSelections;
            }
            set
            {
                if (!ReferenceEquals(_featureSelections, value))
                {
                    var previousValue = _featureSelections as FixupCollection<FeatureSelection>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= FixupFeatureSelections;
                    }
                    _featureSelections = value;
                    var newValue = value as FixupCollection<FeatureSelection>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += FixupFeatureSelections;
                    }
                }
            }
        }
        private ICollection<FeatureSelection> _featureSelections;
    
        public virtual ICollection<Relation> Relations
        {
            get
            {
                if (_relations == null)
                {
                    var newCollection = new FixupCollection<Relation>();
                    newCollection.CollectionChanged += FixupRelations;
                    _relations = newCollection;
                }
                return _relations;
            }
            set
            {
                if (!ReferenceEquals(_relations, value))
                {
                    var previousValue = _relations as FixupCollection<Relation>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= FixupRelations;
                    }
                    _relations = value;
                    var newValue = value as FixupCollection<Relation>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += FixupRelations;
                    }
                }
            }
        }
        private ICollection<Relation> _relations;
    
        public virtual ICollection<Relation> Relations1
        {
            get
            {
                if (_relations1 == null)
                {
                    var newCollection = new FixupCollection<Relation>();
                    newCollection.CollectionChanged += FixupRelations1;
                    _relations1 = newCollection;
                }
                return _relations1;
            }
            set
            {
                if (!ReferenceEquals(_relations1, value))
                {
                    var previousValue = _relations1 as FixupCollection<Relation>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= FixupRelations1;
                    }
                    _relations1 = value;
                    var newValue = value as FixupCollection<Relation>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += FixupRelations1;
                    }
                }
            }
        }
        private ICollection<Relation> _relations1;
    
        public virtual ICollection<GroupRelation_To_Feature> GroupRelations_To_Features_1
        {
            get
            {
                if (_groupRelations_To_Features_1 == null)
                {
                    var newCollection = new FixupCollection<GroupRelation_To_Feature>();
                    newCollection.CollectionChanged += FixupGroupRelations_To_Features_1;
                    _groupRelations_To_Features_1 = newCollection;
                }
                return _groupRelations_To_Features_1;
            }
            set
            {
                if (!ReferenceEquals(_groupRelations_To_Features_1, value))
                {
                    var previousValue = _groupRelations_To_Features_1 as FixupCollection<GroupRelation_To_Feature>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= FixupGroupRelations_To_Features_1;
                    }
                    _groupRelations_To_Features_1 = value;
                    var newValue = value as FixupCollection<GroupRelation_To_Feature>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += FixupGroupRelations_To_Features_1;
                    }
                }
            }
        }
        private ICollection<GroupRelation_To_Feature> _groupRelations_To_Features_1;
    
        public virtual ICollection<GroupRelation_To_Feature> GroupRelations_To_Features1
        {
            get
            {
                if (_groupRelations_To_Features1 == null)
                {
                    var newCollection = new FixupCollection<GroupRelation_To_Feature>();
                    newCollection.CollectionChanged += FixupGroupRelations_To_Features1;
                    _groupRelations_To_Features1 = newCollection;
                }
                return _groupRelations_To_Features1;
            }
            set
            {
                if (!ReferenceEquals(_groupRelations_To_Features1, value))
                {
                    var previousValue = _groupRelations_To_Features1 as FixupCollection<GroupRelation_To_Feature>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= FixupGroupRelations_To_Features1;
                    }
                    _groupRelations_To_Features1 = value;
                    var newValue = value as FixupCollection<GroupRelation_To_Feature>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += FixupGroupRelations_To_Features1;
                    }
                }
            }
        }
        private ICollection<GroupRelation_To_Feature> _groupRelations_To_Features1;
    
        public virtual ICollection<CompositionRule> CompositionRules
        {
            get
            {
                if (_compositionRules == null)
                {
                    var newCollection = new FixupCollection<CompositionRule>();
                    newCollection.CollectionChanged += FixupCompositionRules;
                    _compositionRules = newCollection;
                }
                return _compositionRules;
            }
            set
            {
                if (!ReferenceEquals(_compositionRules, value))
                {
                    var previousValue = _compositionRules as FixupCollection<CompositionRule>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= FixupCompositionRules;
                    }
                    _compositionRules = value;
                    var newValue = value as FixupCollection<CompositionRule>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += FixupCompositionRules;
                    }
                }
            }
        }
        private ICollection<CompositionRule> _compositionRules;
    
        public virtual ICollection<CompositionRule> CompositionRules1
        {
            get
            {
                if (_compositionRules1 == null)
                {
                    var newCollection = new FixupCollection<CompositionRule>();
                    newCollection.CollectionChanged += FixupCompositionRules1;
                    _compositionRules1 = newCollection;
                }
                return _compositionRules1;
            }
            set
            {
                if (!ReferenceEquals(_compositionRules1, value))
                {
                    var previousValue = _compositionRules1 as FixupCollection<CompositionRule>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= FixupCompositionRules1;
                    }
                    _compositionRules1 = value;
                    var newValue = value as FixupCollection<CompositionRule>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += FixupCompositionRules1;
                    }
                }
            }
        }
        private ICollection<CompositionRule> _compositionRules1;

        #endregion
        #region Association Fixup
    
        private void FixupModel(Model previousValue)
        {
            if (previousValue != null && previousValue.Features.Contains(this))
            {
                previousValue.Features.Remove(this);
            }
    
            if (Model != null)
            {
                if (!Model.Features.Contains(this))
                {
                    Model.Features.Add(this);
                }
                if (ModelID != Model.ID)
                {
                    ModelID = Model.ID;
                }
            }
        }
    
        private void FixupAttributes(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (Attribute item in e.NewItems)
                {
                    item.Feature = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (Attribute item in e.OldItems)
                {
                    if (ReferenceEquals(item.Feature, this))
                    {
                        item.Feature = null;
                    }
                }
            }
        }
    
        private void FixupFeatureSelections(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (FeatureSelection item in e.NewItems)
                {
                    item.Feature = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (FeatureSelection item in e.OldItems)
                {
                    if (ReferenceEquals(item.Feature, this))
                    {
                        item.Feature = null;
                    }
                }
            }
        }
    
        private void FixupRelations(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (Relation item in e.NewItems)
                {
                    item.ChildFeature = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (Relation item in e.OldItems)
                {
                    if (ReferenceEquals(item.ChildFeature, this))
                    {
                        item.ChildFeature = null;
                    }
                }
            }
        }
    
        private void FixupRelations1(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (Relation item in e.NewItems)
                {
                    item.ParentFeature = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (Relation item in e.OldItems)
                {
                    if (ReferenceEquals(item.ParentFeature, this))
                    {
                        item.ParentFeature = null;
                    }
                }
            }
        }
    
        private void FixupGroupRelations_To_Features_1(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (GroupRelation_To_Feature item in e.NewItems)
                {
                    item.ChildFeature = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (GroupRelation_To_Feature item in e.OldItems)
                {
                    if (ReferenceEquals(item.ChildFeature, this))
                    {
                        item.ChildFeature = null;
                    }
                }
            }
        }
    
        private void FixupGroupRelations_To_Features1(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (GroupRelation_To_Feature item in e.NewItems)
                {
                    item.ParentFeature = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (GroupRelation_To_Feature item in e.OldItems)
                {
                    if (ReferenceEquals(item.ParentFeature, this))
                    {
                        item.ParentFeature = null;
                    }
                }
            }
        }
    
        private void FixupCompositionRules(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (CompositionRule item in e.NewItems)
                {
                    item.FirstFeature = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (CompositionRule item in e.OldItems)
                {
                    if (ReferenceEquals(item.FirstFeature, this))
                    {
                        item.FirstFeature = null;
                    }
                }
            }
        }
    
        private void FixupCompositionRules1(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (CompositionRule item in e.NewItems)
                {
                    item.SecondFeature = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (CompositionRule item in e.OldItems)
                {
                    if (ReferenceEquals(item.SecondFeature, this))
                    {
                        item.SecondFeature = null;
                    }
                }
            }
        }

        #endregion
    }
}
