//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace DAL.DataEntities
{
    public partial class GroupRelation_To_Feature : IDataEntity
    {
        #region Primitive Properties
    
        public virtual int ID
        {
            get;
            set;
        }
    
        public virtual int GroupRelationID
        {
            get { return _groupRelationID; }
            set
            {
                if (_groupRelationID != value)
                {
                    if (GroupRelation != null && GroupRelation.ID != value)
                    {
                        GroupRelation = null;
                    }
                    _groupRelationID = value;
                }
            }
        }
        private int _groupRelationID;
    
        public virtual int ParentFeatureID
        {
            get { return _parentFeatureID; }
            set
            {
                if (_parentFeatureID != value)
                {
                    if (ParentFeature != null && ParentFeature.ID != value)
                    {
                        ParentFeature = null;
                    }
                    _parentFeatureID = value;
                }
            }
        }
        private int _parentFeatureID;
    
        public virtual int ChildFeatureID
        {
            get { return _childFeatureID; }
            set
            {
                if (_childFeatureID != value)
                {
                    if (ChildFeature != null && ChildFeature.ID != value)
                    {
                        ChildFeature = null;
                    }
                    _childFeatureID = value;
                }
            }
        }
        private int _childFeatureID;

        #endregion
        #region Navigation Properties
    
        public virtual GroupRelation GroupRelation
        {
            get { return _groupRelation; }
            set
            {
                if (!ReferenceEquals(_groupRelation, value))
                {
                    var previousValue = _groupRelation;
                    _groupRelation = value;
                    FixupGroupRelation(previousValue);
                }
            }
        }
        private GroupRelation _groupRelation;
    
        public virtual Feature ChildFeature
        {
            get { return _childFeature; }
            set
            {
                if (!ReferenceEquals(_childFeature, value))
                {
                    var previousValue = _childFeature;
                    _childFeature = value;
                    FixupChildFeature(previousValue);
                }
            }
        }
        private Feature _childFeature;
    
        public virtual Feature ParentFeature
        {
            get { return _parentFeature; }
            set
            {
                if (!ReferenceEquals(_parentFeature, value))
                {
                    var previousValue = _parentFeature;
                    _parentFeature = value;
                    FixupParentFeature(previousValue);
                }
            }
        }
        private Feature _parentFeature;

        #endregion
        #region Association Fixup
    
        private void FixupGroupRelation(GroupRelation previousValue)
        {
            if (previousValue != null && previousValue.GroupRelations_To_Features.Contains(this))
            {
                previousValue.GroupRelations_To_Features.Remove(this);
            }
    
            if (GroupRelation != null)
            {
                if (!GroupRelation.GroupRelations_To_Features.Contains(this))
                {
                    GroupRelation.GroupRelations_To_Features.Add(this);
                }
                if (GroupRelationID != GroupRelation.ID)
                {
                    GroupRelationID = GroupRelation.ID;
                }
            }
        }
    
        private void FixupChildFeature(Feature previousValue)
        {
            if (previousValue != null && previousValue.GroupRelations_To_Features_1.Contains(this))
            {
                previousValue.GroupRelations_To_Features_1.Remove(this);
            }
    
            if (ChildFeature != null)
            {
                if (!ChildFeature.GroupRelations_To_Features_1.Contains(this))
                {
                    ChildFeature.GroupRelations_To_Features_1.Add(this);
                }
                if (ChildFeatureID != ChildFeature.ID)
                {
                    ChildFeatureID = ChildFeature.ID;
                }
            }
        }
    
        private void FixupParentFeature(Feature previousValue)
        {
            if (previousValue != null && previousValue.GroupRelations_To_Features1.Contains(this))
            {
                previousValue.GroupRelations_To_Features1.Remove(this);
            }
    
            if (ParentFeature != null)
            {
                if (!ParentFeature.GroupRelations_To_Features1.Contains(this))
                {
                    ParentFeature.GroupRelations_To_Features1.Add(this);
                }
                if (ParentFeatureID != ParentFeature.ID)
                {
                    ParentFeatureID = ParentFeature.ID;
                }
            }
        }

        #endregion
    }
}
