//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace DAL.DataEntities
{
    public partial class CustomRule : IDataEntity
    {
        #region Primitive Properties
    
        public virtual int ID
        {
            get;
            set;
        }
    
        public virtual int ModelID
        {
            get { return _modelID; }
            set
            {
                if (_modelID != value)
                {
                    if (Model != null && Model.ID != value)
                    {
                        Model = null;
                    }
                    _modelID = value;
                }
            }
        }
        private int _modelID;
    
        public virtual int RuleTypeID
        {
            get { return _ruleTypeID; }
            set
            {
                if (_ruleTypeID != value)
                {
                    if (CustomRule_Type != null && CustomRule_Type.ID != value)
                    {
                        CustomRule_Type = null;
                    }
                    _ruleTypeID = value;
                }
            }
        }
        private int _ruleTypeID;
    
        public virtual string Name
        {
            get;
            set;
        }
    
        public virtual string Expression
        {
            get;
            set;
        }
    
        public virtual string Description
        {
            get;
            set;
        }

        #endregion
        #region Navigation Properties
    
        public virtual CustomRule_Type CustomRule_Type
        {
            get { return _customRule_Type; }
            set
            {
                if (!ReferenceEquals(_customRule_Type, value))
                {
                    var previousValue = _customRule_Type;
                    _customRule_Type = value;
                    FixupCustomRule_Type(previousValue);
                }
            }
        }
        private CustomRule_Type _customRule_Type;
    
        public virtual Model Model
        {
            get { return _model; }
            set
            {
                if (!ReferenceEquals(_model, value))
                {
                    var previousValue = _model;
                    _model = value;
                    FixupModel(previousValue);
                }
            }
        }
        private Model _model;

        #endregion
        #region Association Fixup
    
        private void FixupCustomRule_Type(CustomRule_Type previousValue)
        {
            if (previousValue != null && previousValue.CustomRules.Contains(this))
            {
                previousValue.CustomRules.Remove(this);
            }
    
            if (CustomRule_Type != null)
            {
                if (!CustomRule_Type.CustomRules.Contains(this))
                {
                    CustomRule_Type.CustomRules.Add(this);
                }
                if (RuleTypeID != CustomRule_Type.ID)
                {
                    RuleTypeID = CustomRule_Type.ID;
                }
            }
        }
    
        private void FixupModel(Model previousValue)
        {
            if (previousValue != null && previousValue.CustomRules.Contains(this))
            {
                previousValue.CustomRules.Remove(this);
            }
    
            if (Model != null)
            {
                if (!Model.CustomRules.Contains(this))
                {
                    Model.CustomRules.Add(this);
                }
                if (ModelID != Model.ID)
                {
                    ModelID = Model.ID;
                }
            }
        }

        #endregion
    }
}
