//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace DAL.DataEntities
{
    public partial class CustomRule_Type : IDataEntity
    {
        #region Primitive Properties
    
        public virtual int ID
        {
            get;
            set;
        }
    
        public virtual string Name
        {
            get;
            set;
        }

        #endregion
        #region Navigation Properties
    
        public virtual ICollection<CustomRule> CustomRules
        {
            get
            {
                if (_customRules == null)
                {
                    var newCollection = new FixupCollection<CustomRule>();
                    newCollection.CollectionChanged += FixupCustomRules;
                    _customRules = newCollection;
                }
                return _customRules;
            }
            set
            {
                if (!ReferenceEquals(_customRules, value))
                {
                    var previousValue = _customRules as FixupCollection<CustomRule>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= FixupCustomRules;
                    }
                    _customRules = value;
                    var newValue = value as FixupCollection<CustomRule>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += FixupCustomRules;
                    }
                }
            }
        }
        private ICollection<CustomRule> _customRules;

        #endregion
        #region Association Fixup
    
        private void FixupCustomRules(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (CustomRule item in e.NewItems)
                {
                    item.CustomRule_Type = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (CustomRule item in e.OldItems)
                {
                    if (ReferenceEquals(item.CustomRule_Type, this))
                    {
                        item.CustomRule_Type = null;
                    }
                }
            }
        }

        #endregion
    }
}
