//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.EntityClient;

namespace DAL.DataEntities
{
    public partial class DataEntities : ObjectContext
    {
        public const string ConnectionString = "name=DataEntities";
        public const string ContainerName = "DataEntities";
    
        #region Constructors
    
        public DataEntities()
            : base(ConnectionString, ContainerName)
        {
            this.ContextOptions.LazyLoadingEnabled = true;
        }
    
        public DataEntities(string connectionString)
            : base(connectionString, ContainerName)
        {
            this.ContextOptions.LazyLoadingEnabled = true;
        }
    
        public DataEntities(EntityConnection connection)
            : base(connection, ContainerName)
        {
            this.ContextOptions.LazyLoadingEnabled = true;
        }
    
        #endregion
    
        #region ObjectSet Properties
    
        public ObjectSet<Attribute_DataType> Attribute_DataTypes
        {
            get { return _attribute_DataTypes  ?? (_attribute_DataTypes = CreateObjectSet<Attribute_DataType>("Attribute_DataTypes")); }
        }
        private ObjectSet<Attribute_DataType> _attribute_DataTypes;
    
        public ObjectSet<Attribute> Attributes
        {
            get { return _attributes  ?? (_attributes = CreateObjectSet<Attribute>("Attributes")); }
        }
        private ObjectSet<Attribute> _attributes;
    
        public ObjectSet<Feature> Features
        {
            get { return _features  ?? (_features = CreateObjectSet<Feature>("Features")); }
        }
        private ObjectSet<Feature> _features;
    
        public ObjectSet<Model> Models
        {
            get { return _models  ?? (_models = CreateObjectSet<Model>("Models")); }
        }
        private ObjectSet<Model> _models;
    
        public ObjectSet<User> Users
        {
            get { return _users  ?? (_users = CreateObjectSet<User>("Users")); }
        }
        private ObjectSet<User> _users;
    
        public ObjectSet<Rule_Type> Rule_Types
        {
            get { return _rule_Types  ?? (_rule_Types = CreateObjectSet<Rule_Type>("Rule_Types")); }
        }
        private ObjectSet<Rule_Type> _rule_Types;
    
        public ObjectSet<Rule> Rules
        {
            get { return _rules  ?? (_rules = CreateObjectSet<Rule>("Rules")); }
        }
        private ObjectSet<Rule> _rules;
    
        public ObjectSet<Attribute_Type> Attribute_Types
        {
            get { return _attribute_Types  ?? (_attribute_Types = CreateObjectSet<Attribute_Type>("Attribute_Types")); }
        }
        private ObjectSet<Attribute_Type> _attribute_Types;
    
        public ObjectSet<Relation_Type> Relation_Types
        {
            get { return _relation_Types  ?? (_relation_Types = CreateObjectSet<Relation_Type>("Relation_Types")); }
        }
        private ObjectSet<Relation_Type> _relation_Types;
    
        public ObjectSet<Relation> Relations
        {
            get { return _relations  ?? (_relations = CreateObjectSet<Relation>("Relations")); }
        }
        private ObjectSet<Relation> _relations;
    
        public ObjectSet<GroupRelation_Types> GroupRelation_Types
        {
            get { return _groupRelation_Types  ?? (_groupRelation_Types = CreateObjectSet<GroupRelation_Types>("GroupRelation_Types")); }
        }
        private ObjectSet<GroupRelation_Types> _groupRelation_Types;
    
        public ObjectSet<GroupRelation> GroupRelations
        {
            get { return _groupRelations  ?? (_groupRelations = CreateObjectSet<GroupRelation>("GroupRelations")); }
        }
        private ObjectSet<GroupRelation> _groupRelations;
    
        public ObjectSet<GroupRelations_To_Features> GroupRelations_To_Features
        {
            get { return _groupRelations_To_Features  ?? (_groupRelations_To_Features = CreateObjectSet<GroupRelations_To_Features>("GroupRelations_To_Features")); }
        }
        private ObjectSet<GroupRelations_To_Features> _groupRelations_To_Features;
    
        public ObjectSet<CompositionRule_Type> CompositionRule_Types
        {
            get { return _compositionRule_Types  ?? (_compositionRule_Types = CreateObjectSet<CompositionRule_Type>("CompositionRule_Types")); }
        }
        private ObjectSet<CompositionRule_Type> _compositionRule_Types;
    
        public ObjectSet<CompositionRule> CompositionRules
        {
            get { return _compositionRules  ?? (_compositionRules = CreateObjectSet<CompositionRule>("CompositionRules")); }
        }
        private ObjectSet<CompositionRule> _compositionRules;

        #endregion
    }
}
