//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.EntityClient;

namespace DAL.DataEntities
{
    public partial class DataEntities : ObjectContext
    {
        public const string ConnectionString = "name=DataEntities";
        public const string ContainerName = "DataEntities";
    
        #region Constructors
    
        public DataEntities()
            : base(ConnectionString, ContainerName)
        {
            this.ContextOptions.LazyLoadingEnabled = true;
        }
    
        public DataEntities(string connectionString)
            : base(connectionString, ContainerName)
        {
            this.ContextOptions.LazyLoadingEnabled = true;
        }
    
        public DataEntities(EntityConnection connection)
            : base(connection, ContainerName)
        {
            this.ContextOptions.LazyLoadingEnabled = true;
        }
    
        #endregion
    
        #region ObjectSet Properties
    
        public ObjectSet<Attribute_DataType> Attribute_DataTypes
        {
            get { return _attribute_DataTypes  ?? (_attribute_DataTypes = CreateObjectSet<Attribute_DataType>("Attribute_DataTypes")); }
        }
        private ObjectSet<Attribute_DataType> _attribute_DataTypes;
    
        public ObjectSet<Attribute> Attributes
        {
            get { return _attributes  ?? (_attributes = CreateObjectSet<Attribute>("Attributes")); }
        }
        private ObjectSet<Attribute> _attributes;
    
        public ObjectSet<Feature_Type> Feature_Types
        {
            get { return _feature_Types  ?? (_feature_Types = CreateObjectSet<Feature_Type>("Feature_Types")); }
        }
        private ObjectSet<Feature_Type> _feature_Types;
    
        public ObjectSet<FeatureGroup_Type> FeatureGroup_Types
        {
            get { return _featureGroup_Types  ?? (_featureGroup_Types = CreateObjectSet<FeatureGroup_Type>("FeatureGroup_Types")); }
        }
        private ObjectSet<FeatureGroup_Type> _featureGroup_Types;
    
        public ObjectSet<FeatureGroup> FeatureGroups
        {
            get { return _featureGroups  ?? (_featureGroups = CreateObjectSet<FeatureGroup>("FeatureGroups")); }
        }
        private ObjectSet<FeatureGroup> _featureGroups;
    
        public ObjectSet<Feature> Features
        {
            get { return _features  ?? (_features = CreateObjectSet<Feature>("Features")); }
        }
        private ObjectSet<Feature> _features;
    
        public ObjectSet<Model> Models
        {
            get { return _models  ?? (_models = CreateObjectSet<Model>("Models")); }
        }
        private ObjectSet<Model> _models;
    
        public ObjectSet<User> Users
        {
            get { return _users  ?? (_users = CreateObjectSet<User>("Users")); }
        }
        private ObjectSet<User> _users;
    
        public ObjectSet<Rule_Type> Rule_Types
        {
            get { return _rule_Types  ?? (_rule_Types = CreateObjectSet<Rule_Type>("Rule_Types")); }
        }
        private ObjectSet<Rule_Type> _rule_Types;
    
        public ObjectSet<Rule> Rules
        {
            get { return _rules  ?? (_rules = CreateObjectSet<Rule>("Rules")); }
        }
        private ObjectSet<Rule> _rules;
    
        public ObjectSet<Attribute_Type> Attribute_Types
        {
            get { return _attribute_Types  ?? (_attribute_Types = CreateObjectSet<Attribute_Type>("Attribute_Types")); }
        }
        private ObjectSet<Attribute_Type> _attribute_Types;

        #endregion
    }
}
