//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace DAL.DataEntities
{
    public partial class Feature_Type
    {
        #region Primitive Properties
    
        public virtual int ID
        {
            get;
            set;
        }
    
        public virtual string Name
        {
            get;
            set;
        }
    
        public virtual Nullable<int> FixedLowerBound
        {
            get;
            set;
        }
    
        public virtual Nullable<int> FixedUpperBound
        {
            get;
            set;
        }

        #endregion
        #region Navigation Properties
    
        public virtual ICollection<Feature> Features
        {
            get
            {
                if (_features == null)
                {
                    var newCollection = new FixupCollection<Feature>();
                    newCollection.CollectionChanged += FixupFeatures;
                    _features = newCollection;
                }
                return _features;
            }
            set
            {
                if (!ReferenceEquals(_features, value))
                {
                    var previousValue = _features as FixupCollection<Feature>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= FixupFeatures;
                    }
                    _features = value;
                    var newValue = value as FixupCollection<Feature>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += FixupFeatures;
                    }
                }
            }
        }
        private ICollection<Feature> _features;

        #endregion
        #region Association Fixup
    
        private void FixupFeatures(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (Feature item in e.NewItems)
                {
                    item.Feature_Type = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (Feature item in e.OldItems)
                {
                    if (ReferenceEquals(item.Feature_Type, this))
                    {
                        item.Feature_Type = null;
                    }
                }
            }
        }

        #endregion
    }
}
