//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace DAL.DataEntities
{
    public partial class GroupRelation_Types : IDataEntity
    {
        #region Primitive Properties
    
        public virtual int ID
        {
            get;
            set;
        }
    
        public virtual string Name
        {
            get;
            set;
        }
    
        public virtual Nullable<int> FixedLowerBound
        {
            get;
            set;
        }
    
        public virtual Nullable<int> FixedUpperBound
        {
            get;
            set;
        }

        #endregion
        #region Navigation Properties
    
        public virtual ICollection<GroupRelation> GroupRelations
        {
            get
            {
                if (_groupRelations == null)
                {
                    var newCollection = new FixupCollection<GroupRelation>();
                    newCollection.CollectionChanged += FixupGroupRelations;
                    _groupRelations = newCollection;
                }
                return _groupRelations;
            }
            set
            {
                if (!ReferenceEquals(_groupRelations, value))
                {
                    var previousValue = _groupRelations as FixupCollection<GroupRelation>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= FixupGroupRelations;
                    }
                    _groupRelations = value;
                    var newValue = value as FixupCollection<GroupRelation>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += FixupGroupRelations;
                    }
                }
            }
        }
        private ICollection<GroupRelation> _groupRelations;

        #endregion
        #region Association Fixup
    
        private void FixupGroupRelations(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (GroupRelation item in e.NewItems)
                {
                    item.GroupRelation_Type = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (GroupRelation item in e.OldItems)
                {
                    if (ReferenceEquals(item.GroupRelation_Type, this))
                    {
                        item.GroupRelation_Type = null;
                    }
                }
            }
        }

        #endregion
    }
}
