//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace DAL.DataEntities
{
    public partial class Model : IDataEntity
    {
        #region Primitive Properties
    
        public virtual int ID
        {
            get;
            set;
        }
    
        public virtual int UserID
        {
            get { return _userID; }
            set
            {
                if (_userID != value)
                {
                    if (User != null && User.ID != value)
                    {
                        User = null;
                    }
                    _userID = value;
                }
            }
        }
        private int _userID;
    
        public virtual string Name
        {
            get;
            set;
        }
    
        public virtual Nullable<System.DateTime> CreatedDate
        {
            get;
            set;
        }
    
        public virtual Nullable<System.DateTime> LastModifiedDate
        {
            get;
            set;
        }

        #endregion
        #region Navigation Properties
    
        public virtual ICollection<Feature> Features
        {
            get
            {
                if (_features == null)
                {
                    var newCollection = new FixupCollection<Feature>();
                    newCollection.CollectionChanged += FixupFeatures;
                    _features = newCollection;
                }
                return _features;
            }
            set
            {
                if (!ReferenceEquals(_features, value))
                {
                    var previousValue = _features as FixupCollection<Feature>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= FixupFeatures;
                    }
                    _features = value;
                    var newValue = value as FixupCollection<Feature>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += FixupFeatures;
                    }
                }
            }
        }
        private ICollection<Feature> _features;
    
        public virtual User User
        {
            get { return _user; }
            set
            {
                if (!ReferenceEquals(_user, value))
                {
                    var previousValue = _user;
                    _user = value;
                    FixupUser(previousValue);
                }
            }
        }
        private User _user;
    
        public virtual ICollection<Rule> Rules
        {
            get
            {
                if (_rules == null)
                {
                    var newCollection = new FixupCollection<Rule>();
                    newCollection.CollectionChanged += FixupRules;
                    _rules = newCollection;
                }
                return _rules;
            }
            set
            {
                if (!ReferenceEquals(_rules, value))
                {
                    var previousValue = _rules as FixupCollection<Rule>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= FixupRules;
                    }
                    _rules = value;
                    var newValue = value as FixupCollection<Rule>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += FixupRules;
                    }
                }
            }
        }
        private ICollection<Rule> _rules;
    
        public virtual ICollection<Relation> Relations
        {
            get
            {
                if (_relations == null)
                {
                    var newCollection = new FixupCollection<Relation>();
                    newCollection.CollectionChanged += FixupRelations;
                    _relations = newCollection;
                }
                return _relations;
            }
            set
            {
                if (!ReferenceEquals(_relations, value))
                {
                    var previousValue = _relations as FixupCollection<Relation>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= FixupRelations;
                    }
                    _relations = value;
                    var newValue = value as FixupCollection<Relation>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += FixupRelations;
                    }
                }
            }
        }
        private ICollection<Relation> _relations;

        #endregion
        #region Association Fixup
    
        private void FixupUser(User previousValue)
        {
            if (previousValue != null && previousValue.Models.Contains(this))
            {
                previousValue.Models.Remove(this);
            }
    
            if (User != null)
            {
                if (!User.Models.Contains(this))
                {
                    User.Models.Add(this);
                }
                if (UserID != User.ID)
                {
                    UserID = User.ID;
                }
            }
        }
    
        private void FixupFeatures(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (Feature item in e.NewItems)
                {
                    item.Model = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (Feature item in e.OldItems)
                {
                    if (ReferenceEquals(item.Model, this))
                    {
                        item.Model = null;
                    }
                }
            }
        }
    
        private void FixupRules(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (Rule item in e.NewItems)
                {
                    item.Model = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (Rule item in e.OldItems)
                {
                    if (ReferenceEquals(item.Model, this))
                    {
                        item.Model = null;
                    }
                }
            }
        }
    
        private void FixupRelations(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (Relation item in e.NewItems)
                {
                    item.Model = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (Relation item in e.OldItems)
                {
                    if (ReferenceEquals(item.Model, this))
                    {
                        item.Model = null;
                    }
                }
            }
        }

        #endregion
    }
}
