//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace DAL.DataEntities
{
    public partial class Relation_Type : IDataEntity
    {
        #region Primitive Properties
    
        public virtual int ID
        {
            get;
            set;
        }
    
        public virtual string Name
        {
            get;
            set;
        }
    
        public virtual Nullable<int> FixedLowerBound
        {
            get;
            set;
        }
    
        public virtual Nullable<int> FixedUpperBound
        {
            get;
            set;
        }

        #endregion
        #region Navigation Properties
    
        public virtual ICollection<Relation> Relations
        {
            get
            {
                if (_relations == null)
                {
                    var newCollection = new FixupCollection<Relation>();
                    newCollection.CollectionChanged += FixupRelations;
                    _relations = newCollection;
                }
                return _relations;
            }
            set
            {
                if (!ReferenceEquals(_relations, value))
                {
                    var previousValue = _relations as FixupCollection<Relation>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= FixupRelations;
                    }
                    _relations = value;
                    var newValue = value as FixupCollection<Relation>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += FixupRelations;
                    }
                }
            }
        }
        private ICollection<Relation> _relations;

        #endregion
        #region Association Fixup
    
        private void FixupRelations(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (Relation item in e.NewItems)
                {
                    item.Relation_Type = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (Relation item in e.OldItems)
                {
                    if (ReferenceEquals(item.Relation_Type, this))
                    {
                        item.Relation_Type = null;
                    }
                }
            }
        }

        #endregion
    }
}
